# Generated by Django 4.0 on 2022-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('userType', models.CharField(max_length=100)),
            ],
        ),
    ]
